#https://github.com/compose-spec/compose-spec/blob/main/spec.md#compose-fileよりversionの記載は不要との事。
#version: '3.8'

services:
  # PostgreSQL データベース
  postgres:
    # 15.4->17.6に変更。本番のバージョンに合わせる。
    # https://hub.docker.com/_/postgresも参照
    image: postgres:17.6
    container_name: my-portfolio-postgres
    environment:
      POSTGRES_USER: portfolio_admin
      POSTGRES_PASSWORD: local_dev_password
      POSTGRES_DB: portfolio_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U portfolio_admin"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - portfolio-network

  # Redis (将来のWebSocketセッション管理用)
  redis:
    # 7.1-alpine->7に変更。alpineではない方を使用。
    # https://hub.docker.com/_/redisも参照
    image: redis:7
    container_name: my-portfolio-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - portfolio-network

  # Go API アプリケーション
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: my-portfolio-api
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=portfolio_admin
      - DB_PASSWORD=local_dev_password
      - DB_NAME=portfolio_db
      - DB_SSLMODE=disable
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - portfolio-network
    volumes:
      - .:/app
      - /app/vendor
    working_dir: /app
    command: go run -mod=mod ./cmd/api  # -mod=modフラグを追加

  # LocalStack (SQS用)テスト用に追加。260108byKota
  localstack:
    image: localstack/localstack:latest
    container_name: my-portfolio-localstack
    ports:
      - "4566:4566"            # LocalStack のエッジポート
    environment:
      - SERVICES=sqs           # SQSサービスのみ有効化
      - ENFORCE_IAM=0          # これが 1 になっていると test 認証を拒絶する
      - DEFAULT_REGION=ap-northeast-1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./localstack:/var/lib/localstack"
      # - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  postgres_data:
  redis_data:

networks:
  portfolio-network:
    driver: bridge